### ISSUE TITLE
New skins

### ISSUE THREAD

**Issue by Weeeishy** [xSpikeisDEADx/csgo_wpaints#1]
Hey!

Can you please update the cfg file with the new skins? Thanks

**Comment by xSpikeisDEADx** [comment]
Hey, just updated the cfg file, it should be good now.
Hit me up on steam, my name is: Principle
(The one with P,C Principle as his Profile Picture)
http://steamcommunity.com/id/spike890/

**Comment by Weeeishy** [comment]
Thank man, much appreciated. <3
